# Hands-on NumPy
---
Welcome to the second session of the DSC ML Talks event!. 

In this hands-on workshop on NumPy, we will be covering some of the most important concepts of the PyData module NumPy. 

This notebook contains many exercise as well based on the topics that will be covered in this session. We want you to attempt those exercises after this session ends, and make your submissions in a Google Form to be shared at the end of this session. 

### Import NumPy
---

In order to use NumPy in your python projects, the first step is to import the NumPy mudule. Here is how you do that.

In [1]:
# importing numpy
import numpy as np

In [ ]:
# enter code here
list1=list(range(1,22))
arr=np.array(list1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [ ]:
x = list(range(10)) # this creates a list of length 10 with elements from 0 to 10
x

We already know what python lists are, and how they work. So let's now use the list __x__ that we declated above, and covert into a NumPy array.



In [ ]:
# creating a numpy array using a python list
x_arr = np.array(x)
x_arr

Next up, let's take a look at lists and arrays.

## Arrays in NumPy
---

* Arrays are the most distinguishing feature of the NumPy module.
* Can be thought of as a substitute of Python lists.
* NumPy arrays are MUCH faster than Python lists. 

If we talk in mathematical terminology, a 1-D array represents a vector and a 2-D array represents a matrix.

### EXERCISE: Create any python list of your choice and the print a NumPy array using the python list 

Now one very important thing to note is that lists and numpy arrays are different because in lists you can have any types of values, it can be an int, a string, a float, etc. __But numpy array can only contain elements of a single data-type__ and it will upcast if the types don't match. 

Let us see how this works.

In [ ]:
z = np.array([10, 100, 1000.0, 113]) # 3rd element, 1000.0 is a floating point number
z

As you can see we passed in a float value along with the different integer values and the resultant array was one which contained all float values. So the integer values were typecasted to floats as well.


Here are some more important numpy functions that might come in handy.

* __np.zeros(shape, dtype)__ = This helps in creating an array of zeroes where length is equal to the length of the array we want and dtype is the data type of the elements in the array. You can also pass in the dimensions of the array that you wish to have.

* __np.ones(shape, dtype)__ = This helps in creating an array of ones where length is equal to the length of the array we want and dtype is the data type of the elements in the array. You can also pass in the dimensions of the array that you wish to have.

* __np.arange(start, end, step)__ = This helps in creating an array of elements starting from the 'start' and going till the end with taking the specified number of steps in between.

* __np.linspace(start, end)__ = This creates an array of evenly spaced elements.

* __np.random.randint(start, end, shape)__ = This creates an array of the dimensions that we provide and the the elements are random numbers betweent the start and the end.

In [ ]:
np.zeros(5, dtype = int)

In [ ]:
np.ones((3, 4), dtype=int)

In [ ]:
np.arange(0, 5, 2)

In [ ]:
np.linspace(0, 10, 5)

In [ ]:
np.random.randint(0, 20, (3, 3)) # Create a 3x3 array of random integers in the interval [0, 20]

### EXERCISE: Create 10 equal intervals between 30 to 90.
Hint: Which NumPy method can be used to divide a range into buckets?

In [ ]:
# enter code here
arr=np.linspace(30,90,10)
arr

### EXERCISE: Create a numpy array of random integers between 40 to 200, containing 6 rows and 2 columns. 

In [ ]:
# enter code here
arr=np.random.randint(40,200,size=(6,2))
arr

Let's go ahead and do some more operations using NumPy.

First let us have a look at the random.randn module. 

The __randn__ function returns an array containing values (or "samples") from a standard normal distribution.

* __np.random.randn(shape)__

__NOTE:__ Shape is not a tuple here (unlike some other NumPy methods) but simply comma separated integer values. 

In [ ]:
a = np.random.randn(3,4)
a

### EXERCISE: Create a vector ex_mat1 of 10 elements with random samples from the normal distribution.

In [ ]:
# write code here
ex_mat1=np.random.randn(1,10)
ex_mat1

### EXERCISE: Create a matrix ex_mat2 (2 rows, 3 cols) with random values from the normal distribution.



In [16]:
# write code here
ex_mat2=np.random.randn(2,3)
ex_mat2

array([0.5675075 , 1.88112519])

Now, let us define 2 more matrices x1 and x2.

In [ ]:
x1 = np.random.randint(0, 100, (4,5))
x2 = np.random.rand(10)
x1, x2

We will use the above defined x1 and x2 and use them to understand methods like 'ndim', 'shape' and 'size

In [ ]:
print("Dimensions of x2 are:",x2.ndim) # number of dimensions

print("Shape of x2 is:",x2.shape) # shape of the array

print("Size of x2 is:",x1.size) # number of elements in the array

print("The data type of x2 is:",x2.dtype) # data-type of elements in the array

Now that we know some basic operations, let's take a look at a very important topic - Indexing!

Let's use the arrays x1 and x2 for this as well

In [ ]:
x1 

In [30]:
x2 

array([6.03608664e-01, 7.36966388e-01, 6.39668677e-01, 3.51000000e+02,
       3.45354959e-01, 2.72642594e-01, 4.49825615e-01, 1.00041005e-02,
       4.16165267e-01, 1.02696458e-01])

The indexing starts from 0 so when say we want the element at the 0th position, we are trying to access the very first element in the array.

In [ ]:
print("The first element of x2 is:", x2[0])

print("The second element of x2 is:", x2[1])

print("The element at the position (0,0) of x1 is:", x1[0,0])

print("The element at the position (3,3) of x1 is:", x1[2,2])

Now, let us assume that we want the print the last element of an array, however the catch here is that we don't know the length of the array. 

In NumPy arrays, just like Python lists, indexing from the end starts from index value __-1__. That is, _arr[-1]_ will print the last element of the numpy array _arr_, _arr[-2]_ will print second last element of arr, so on and so forth. 

In [26]:
# printing last element of array x2
x2[-1]

0.10269645794509341

### EXERCISE: Print the second last element in the last row of x1.

In [23]:
# enter code here
x1[-1,-2]

35

We can use these indices to even change the values of elements in our array. We will change the first element in row 1 of the array x1 to over 9000.

In [ ]:
x1[0, 0] = 9001
x1

### EXERCISE: Set the 4th element in x2 as 351 and print the result.

In [ ]:
# enter code here
x2[3]=351
x2

Next up, we will see how array slicing works. We can use our x1 and x2 to learn about array slicing as well.

In [ ]:
x2[0:5] # this gives us the first 5 elements in our array 

This can also be written as:

In [ ]:
x2[:5]

In [ ]:
x2[::2] # gives us every other element in our array

In [ ]:
x2[::-1] # reverses the whole array for us

Let's try the same with multi-dimensional arrays

In [ ]:
x1[:, 0]  # retrieve the first column

In [ ]:
print(x1[:, :2]) # retrieving the first 2 columns

print(x2[:]) # gives us all the elements in the array x2

print(x1[-1, :])

### EXERCISE: Make two new numpy arrays y1 and y2 with random integer values of length 10. Then add reverse of y1 to reverse of y2

In [ ]:
# enter code here
y1=np.random.randint(20, 150, size=10)
y2=np.random.randint(20, 150, size=10)
y1=y1[::-1]
y2=y2[::-1]
y1+y2


Now we will take a look at __reshape__. The reshape method allows us to modify (or view a mutated view of the array values, to be more precise) the shape of a NumPy array once it has been declared.

In [34]:
arr = np.array([10,20,30,40,50,60,70,80,90])
arr.shape

(9,)

In [35]:
arr.reshape((3, 3))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

So we defined a one dimensional array first and then converted it into a 2d array using reshape. This also can be done using __newaxis__ method but reshape works just fine and is kind of more self-explanatory.

Now, let us have a look at how to concatenate two arrays.

In [36]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([4, 5, 6, 7, 8])

np.concatenate([arr1, arr2])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

You can do the same for multi-dimensional array.

__NOTE:__ The default axis for concatenation is __axis = 0__, i.e., along the row axis. In order to concatenate along the column axis, you have to specify the __axis__ argument.

In [51]:
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr4 = np.array([[6, 7, 8],
                 [7, 8, 9]])

print(np.concatenate([arr3, arr4])) # default axis = 0

print(np.concatenate([arr3, arr4], axis=1)) # concatenation along column axis


[[1 2 3]
 [4 5 6]
 [6 7 8]
 [7 8 9]]
[[1 2 3 6 7 8]
 [4 5 6 7 8 9]]


### EXERCISE : Make two multidimensional arrays a1 of shape(5, 2) , a2 of shape(5, 2) and concatenate them along the column axis.  

In [58]:
# enter code here
a1=np.random.randint(10,190,size=10)
a1.resize((5,2))
a2=np.random.randint(10,190,size=10)
a2.resize((5,2))
np.concatenate((a1,a2),axis=1)

array([[144, 173, 183, 144],
       [107, 100,  13, 176],
       [115,  16, 110,  82],
       [ 32,  90,  49,  38],
       [ 60,  86, 144, 115]])

Now let us have a look at some other aggregation methods in NumPy.

In [59]:
print("The smallest element in arr1 is:", np.min(arr1))

print("The largest element in arr1 is:", np.max(arr1))

print("The sum of all elements in arr1 is:", np.sum(arr1))

The smallest element in arr1 is: 1
The largest element in arr1 is: 5
The sum of all elements in arr1 is: 15


We can carry out a similar thing for multi-dimensional arrays as well.

In [60]:
print("The smallest element in arr3 is:", np.min(arr3))

print("The largest element in arr3 is:", np.max(arr3))

print("The sum of all elements in arr3 is:", np.sum(arr3))

The smallest element in arr3 is: 1
The largest element in arr3 is: 6
The sum of all elements in arr3 is: 21


### EXERCISE : Find the maximum element in 1st row of arr3.
Hint: Recall how to retrieve the rows in a multidimensional array using indexing.

In [64]:
# enter code here
np.max(arr3[0,:])

3

Next up, we will see how does broadcasting works in NumPy.

In [ ]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

a + b

Adding a scalar to an array:

In [ ]:
a = a + 5
a

Adding arrays of different shapes:

In [66]:
M = np.ones((2, 3))
A = np.arange(3)

print(M)
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [67]:
M + A

array([[1., 2., 3.],
       [1., 2., 3.]])

Now, let's see how comparison operators work in NumPy.

In [ ]:
a

In [ ]:
a < 12 # compares all the elements in 'a' to see if the element is smaller than 12 and if yes it returns True or else False

Next up let's explore some fancy indexing.

In [ ]:
X = np.array([10, 20, 30, 45, 65, 67, 64, 3, 56, 74, 29])

In [ ]:
[X[3], X[4], X[10]] # grab the elements in X at positions 3, 4 and 10

In [ ]:
j = [3, 4, 10] # another way to do the above operation
X[j]

In [77]:
y1 = np.arange(25).reshape(5, 5)
y1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [80]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
y1[row, col]

array([ 2,  6, 13])

In this we defined a 5x5 matrix and we defined the row and the column variables in order to perform fancy indexing. 

We can also use fancy indexing to manipulate the values in our array.

In [81]:
x = np.arange(20)
i = np.array([3, 4, 7, 9])
x[i] = 100
print(x)

[  0   1   2 100 100   5   6 100   8 100  10  11  12  13  14  15  16  17
  18  19]


Next let's take a look at sorting using NumPy.

In [ ]:
x = np.array([4, 5, 6, 32, 5, 7, 8, 1])
np.sort(x)

Here we returned elements but we can use argsort in order to return the indices of the sorted elements.

In [82]:
np.argsort(x)

array([ 0,  1,  2,  5,  6,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  4,
        3,  7,  9])

We can also do row and column wise sorting in a matrix.

In [86]:
x = np.random.randint(0, 25, (5, 5))
print(x)

[[ 4 16 18  2 22]
 [24 24  2 22  1]
 [19  9 24 10 14]
 [ 2 24 20  4  9]
 [11  2  5 21  1]]


In [ ]:
np.sort(x, axis=0) # sorting all elements of the column

In [87]:
np.sort(x, axis=1) # sorting all elements of the row

array([[ 2,  4, 16, 18, 22],
       [ 1,  2, 22, 24, 24],
       [ 9, 10, 14, 19, 24],
       [ 2,  4,  9, 20, 24],
       [ 1,  2,  5, 11, 21]])

### EXERCISE: Sort all elements of matrix m1 firstly column wise then row wise

In [83]:
m1 = np.random.randint(0, 100, (7,5))
m1

array([[52, 29, 41, 63, 54],
       [10, 96, 70,  4, 29],
       [60, 41,  9, 58, 26],
       [85,  9, 58, 98, 24],
       [14, 20, 79, 31,  9],
       [15, 33, 29, 37, 28],
       [ 5, 12, 73, 80, 81]])

In [89]:
# enter code here
print(np.sort(m1,axis=0))
print()
print(np.sort(m1,axis=1))

[[ 5  9  9  4  9]
 [10 12 29 31 24]
 [14 20 41 37 26]
 [15 29 58 58 28]
 [52 33 70 63 29]
 [60 41 73 80 54]
 [85 96 79 98 81]]

[[29 41 52 54 63]
 [ 4 10 29 70 96]
 [ 9 26 41 58 60]
 [ 9 24 58 85 98]
 [ 9 14 20 31 79]
 [15 28 29 33 37]
 [ 5 12 73 80 81]]


With this we come to an end to the NumPy section! Congrats on finishing this tutorial!